version: '3.8'
services:
  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    depends_on:
      - postgres
    build:
      context: .
      target: builder
    command: sh -c -f "yarn run start:prod"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src/:/app/src/
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
volumes: 
  postgres: